quarto/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.conf.urls.defaults import patterns, include, url
from views import *

urlpatterns = patterns(
    '',
    url(r'^$', ListaQuarto.as_view()),
    url(r'^add/$', AddQuarto.as_view()),
    url(r'^atualiza/(?P<pk>\d+)/$', AtualizaQuarto.as_view()),
    url(r'^hospedar/(?P<pk>\d+)/$', InicarEstadiaQuarto.as_view()),
    url(r'^remove/(?P<pk>\d+)/$', RemoveQuarto.as_view()),
    url(r'^dano/(?P<pk>\d+)/$', AdicinarDanoQuarto.as_view()),
    url(r'^consumo/(?P<pk>\d+)/$', ConsumoQuarto.as_view()),
    url(r'^finalizar/(?P<pk>\d+)/$', FinalizarQuarto.as_view()),
    url(r'^relatorio/$', RelatorioEstadiasView.as_view()),
    url(r'^estadia/(?P<pk>\d+)/$', DetalheEstadia.as_view()),
)

urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^$', 'hotsys.views.home', name='home'),
    url(r'^produto/', include('hotsys.produto.urls')),
)

quarto/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


import datetime
from django.db import models
from hospede.models import Hospede
from django.db.models import Sum
from decimal import Decimal

QUARTO_ESTADOS = (
    ('l', "Livre"),
    ('o', "Ocupado"),
    ('r', "Reservado"),
    ('m', u"Manutenção"))

class Quarto(models.Model):
    nome = models.CharField(
        max_length=150,
        verbose_name="Nome")

    preco = models.DecimalField(
        decimal_places=2, max_digits=10,
        verbose_name="Preço")
    
    num_leitos = models.IntegerField(
        verbose_name=u"Número de leitos")
    suite = models.BooleanField(
        verbose_name="é suite")
    cama_casal = models.BooleanField(
        verbose_name="Possui cama de casal")
    estado = models.CharField(max_length=1,
                              choices=QUARTO_ESTADOS,
                              default='l')

    estadia_atual = models.ForeignKey(
        "Estadia",
        blank=True, null=True,
        related_name="estadia atual")

    class Meta:
        db_table = "quarto"
        ordering = ['nome']


    def tem_reserva(self, data_inicial, data_final):
        """
        Retorna se o quarto atual possui reserva.
        """
        from reserva.models import Reserva

        return Reserva.objects.filter(
            models.Q(data_inicial__range=(data_inicial, data_final))|
            models.Q(data_final__range=(data_inicial, data_final))).count() > 0

class Estadia(models.Model):
    data_inicial = models.DateTimeField()
    data_final = models.DateTimeField(blank=True, null=True)
    finalizada = models.BooleanField(default=False)
    hospedes = models.ManyToManyField(Hospede)
    quarto = models.ForeignKey(Quarto,
                               related_name="quarto utilizada")

    pre_pago = models.DecimalField(
        decimal_places=2, max_digits=10,
        verbose_name="Valor pré-pago",
        blank=True, null=True)

    class Meta:
        db_table = "estadia"

    @property
    def qtde_dias(self):
        """
        Retorna quantidade de dias hospedados
        """
        
        if self.finalizada:
            f = self.data_final
        else:
            f = datetime.datetime.now()

        dias = (f - self.data_inicial).days

        if f.time() > datetime.time(14, 00):
            dias += 1

        if dias == 0:
            return 1
        else:
            return dias

    @property
    def danos(self):
        """
        Retorna a lista de danos da estadia
        """
        return Dano.objects.filter(estadia=self)

    @property
    def produtos(self):
        """
        Retorna a lista de produtos utilizados
        """
        from hotsys.produto.models import ProdutoItem
        return ProdutoItem.objects.filter(estadia=self)

    @property
    def total_danos(self):
        """
        Retorna o valor total de danos
        """
        data = self.danos.aggregate(Sum('valor'))
        return data['valor__sum']

    @property
    def total_produtos(self):
        """
        Retorna o valor total de danos
        """
        data = self.produtos.aggregate(Sum('valor_total'))
        return data['valor_total__sum']

    @property
    def total_estadia(self):
        """
        Retorna o valor das estadias
        """
        return self.qtde_dias * self.quarto.preco

    @property
    def valor_total(self):
        """
        Valor total dos serviços
        hospedagem + produtos + danos
        """
        total = Decimal('0.00')
        t_danos = self.total_danos
        t_produtos = self.total_produtos
        t_estadia = self.total_estadia

        if t_danos:
            total += t_danos

        if t_produtos:
            total += t_produtos

        if t_estadia:
            total += t_estadia

        return total

    @property
    def total_pagar(self):
        """
        Total a pagar da estadia
        considerando o valor pré-pago na reserva
        """
        total = self.valor_total

        if self.pre_pago:
            total -= self.pre_pago

        return total

    def finalizar(self):
        self.data_final = datetime.datetime.now()
        self.finalizada = True
        self.save()

        self.quarto.estadia_atual = None
        self.quarto.estado = 'l' #Livre
        self.quarto.save()


    def get_absolute_url(self):
        return "/quarto/estadia/%d/" % self.id

class Dano(models.Model):
    estadia = models.ForeignKey("Estadia")
    desc = models.CharField(
        max_length=200,
        verbose_name=u"Descrição")

    valor = models.DecimalField(
        decimal_places=2, max_digits=10,
        verbose_name="Valor")

    grave = models.BooleanField(
        verbose_name="Grave")

    class Meta:
        db_table = "dano"


class RelatorioEstadiasMes(object):
    def __init__(self, mes):
        self.mes = mes
        self.queryset = Estadia.objects.filter(
            finalizada=True,
            data_inicial__year=mes.year,
            data_inicial__month=mes.month)

    def __iter__(self):
        return self.queryset.__iter__()
        
class RelatorioEstadias(object):
    def __init__(self):
        self.parts = [
            RelatorioEstadiasMes(d)
            for d in
            Estadia.objects.filter(finalizada=True).dates(
                'data_inicial', 'month', order='DESC')]


    def __iter__(self):
        return self.parts.__iter__()

quarto/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

__all__ = ("QuartoForm", "InicarEstadiaForm", "RegistrarDanoForm",
           "RegistrarConsumoForm", "AddConsumoForm")

import datetime

from django import forms
from models import *
from fields import HospedesField, ProdutosField
from hotsys.produto.models import Produto

class QuartoForm(forms.ModelForm):
    class Meta:
        model = Quarto
        exclude = ('estadia_atual', 'estado')


class InicarEstadiaForm(forms.Form):
    data_inicial = forms.DateField(
        label="Data inicial",
        input_formats=('%d/%m/%Y',),
        initial=datetime.date.today,
        widget=forms.DateInput(format='%d/%m/%Y'))

    data_final = forms.DateField(
        label="Data final",
        input_formats=('%d/%m/%Y',),
        widget=forms.DateInput(format='%d/%m/%Y'))
    
    reserva = forms.CharField(
        widget=forms.HiddenInput,
        required=False)

    hospede = HospedesField()

    def clean_hospede(self):
        data = self.cleaned_data['hospede']
        return Hospede.objects.in_bulk(data).values()

    def set_reserva(self, reserva):
        self.initial['data_inicial'] = reserva.data_inicial
        self.initial['data_final'] = reserva.data_final
        self.initial['reserva'] = reserva.id

class RegistrarDanoForm(forms.ModelForm):
    class Meta:
        model = Dano
        exclude = ('estadia',)

class RegistrarConsumoForm(forms.Form):
    produto = ProdutosField()

    def clean_produto(self):
        data = self.cleaned_data['produto']
        qtdes = {}
        
        for d in data:
            id, qtde = d.split('-')
            qtdes[int(id)] = int(qtde)
        
        prods = Produto.objects.in_bulk(qtdes.keys())

        return [(v, qtdes[k]) for k, v in prods.iteritems()]


    def save(self, *args, **kwargs):
        return self.cleaned_data['produto']

class AddConsumoForm(forms.Form):
    produto = forms.ChoiceField(
        label="Produto")

    qtde = forms.IntegerField(
        initial=1,
        label="Quantidade")


    def __init__(self, *args, **kwargs):
        super(AddConsumoForm, self).__init__(*args, **kwargs)
        choices = [(p.id, p.nome) for p in Produto.objects.all()]

        self.fields['produto'].choices = [('', '-----')] +choices

quarto/templates/quarto/consumo.html
{% extends "base.html" %}
{% block title %}Registrar consumo{% endblock %}
{% block extrahead %}
<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/static/js/consumo.js"></script>

<style type="text/css">
  #id_qtde {width: 50px;}
</style>
<link type="text/css" href="/static/css/smoothness/jquery-ui-1.8.18.custom.css" rel="stylesheet" />
{% endblock %}
{% block conteudo %}
<h3>Registrar consumo</h3>

<table>
  <tr>
    <th>{{ add_form.produto.label }}:</th>
    <td>{{ add_form.produto }}</td>
    
    <th>{{ add_form.qtde.label }}:</th>
    <td>{{ add_form.qtde }}</td>

    <td><input id="add_produto" class="button green" type="button" value="Adicionar" /></td>
  </tr>
</table>

<form method="post" action=".">
  {% csrf_token %}
  {{ form.errors }}
  <table id="consumo_table" class="list">
    <thead>
      <tr><th>Nome</th><th>Valor Unitário</th><th>Valor Total</th><th>&nbsp</th></tr>
    </thead>
    <tbody>
    </tbody>
  </table>

  <input type="submit" value="Registrar" />
</form>
{% endblock %}

quarto/templates/quarto/estadia_detail.html
{% extends "base.html" %}
{% block title %}Detalhes da Estadia{% endblock %}

{% block conteudo %}
<h2>Detalhes da Estadia</h2>

<table class="list">
  <tbody>
    <tr>
      <th>Data inicial:</th>
      <td>{{ object.data_inicial|date:"d/m/Y" }}</td>
    </tr><tr>
      <th>Data final:</th>
      <td>{{ object.data_final|date:"d/m/Y" }}</td>
    </tr><tr>
      <th>Quantidade de dias hóspedados:</th>
      <td>{{ estadia.qtde_dias }}</td>
    </tr><tr>
      <th>Finalizada:</th>
      <td>{% if object.finalizada %}Sim{% else %}Não{% endif %}</td>
    </tr><tr>
      <th>Quarto:</th>
      <td>{{ object.quarto.nome }}</td>
    </tr>
    <tr>
      <th>Valor total:</th>
      <td>{{ estadia.valor_total|floatformat:"2" }}</td>
    </tr>
    {% if estadia.pre_pago %}
    <tr>
      <th>Valor adiantado (reserva):</th>
      <td> - {{ estadia.pre_pago|floatformat:"2" }}</td>
    </tr>
    {% endif %}
    <tr>
      <th>Total a pagar:</th>
      <td>{{ estadia.total_pagar|floatformat:"2" }}</td>
    </tr>
  </tbody>
</table>

<table class="list">
  <thead>
    <tr>
      <th colspan="2">
        <h4>Hóspedes</h4>
      </th>
    </tr>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
    </tr>
  </thead>

  <tbody>
    {% for h in object.hospedes.all %}
    <tr>
      <td>{{ h.nome }}</td>
      <td>{{ h.cpf }}</td>
    </tr>
    {% endfor %}
  </tbody>
  
</table>

{% if object.produtos %}
<table class="list">
  <thead>
    <tr>
      <th colspan="3">
        <h4>Produtos consumidos</h4>
      </th>
    </tr>
    <tr>
      <th>Descrição</th>
      <th>Quantidade</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    {% for p in object.produtos %}
    <tr>
      <td>{{ p.produto.nome }}</td>
      <td>{{ p.qtde }}</td>
      <td>{{ p.valor_total|floatformat:"2" }}</td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td>&nbsp</td><td>Total</td>
      <td>{{ estadia.total_produtos|floatformat:"2" }}</td>
    </tr>
  </tfoot>
</table>
{% endif %}

{% if object.danos %}
<table class="list">
  <thead>
    <tr>
      <th colspan="3">
        <h4>Danos realizados</h4>
      </th>
    </tr>
    <tr>
      <th>Descrição</th>
      <th>Grave</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    {% for d in object.danos %}
    <tr>
      <td>{{ d.desc }}</td>
      <td>{% if d.grave %}Sim{% else %}Não{% endif %}</td>
      <td>{{ d.valor|floatformat:"2" }}</td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td>&nbsp</td><td>Total</td>
      <td>{{ estadia.total_danos|floatformat:"2" }}</td>
    </tr>
  </tfoot>
</table>
{% endif %}

{% endblock %}

quarto/templates/quarto/finalizar.html
{% extends "base.html" %}
{% block title %}Finalizar Estadia{% endblock %}

{% block conteudo %}
<h3>Finalizar estadia</h3>

<table class="list">
  <tr>
    <td>Data inicial:</td>
    <td>{{ estadia.data_inicial|date:"d/m/Y" }}</td>
  </tr><tr>
    <td>Quantidade de dias hóspedados:</td>
    <td>{{ estadia.qtde_dias }}</td>
  </tr><tr>
    <td>Total pela estadia:</td>
    <td>{{ estadia.total_estadia|floatformat:"2" }}</td>
  </tr>
  <tr>
    <td>Total a pagar:</td>
    <td>{{ estadia.total_pagar|floatformat:"2" }}</td>
  </tr>
  <tr>
    <td>&nbsp</td>
    <td>
      <form action="." method="post">
        {% csrf_token %}
        <input class="button red" type="submit" value="Finalizar Estadia" /></td>
    </form>
  </tr>
</table>

<table class="list">
  <thead>
    <tr>
      <th colspan="2">
        <h4>Hóspedes</h4>
      </th>
    </tr>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
    </tr>
  </thead>

  <tbody>
    {% for h in estadia.hospedes.all %}
    <tr>
      <td>{{ h.nome }}</td>
      <td>{{ h.cpf }}</td>
    </tr>
    {% endfor %}
  </tbody>
  
</table>


{% if estadia.produtos %}
<table class="list">
  <thead>
    <tr>
      <th colspan="3">
        <h4>Produtos consumidos</h4>
      </th>
    </tr>
    <tr>
      <th>Descrição</th>
      <th>Quantidade</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    {% for p in estadia.produtos %}
    <tr>
      <td>{{ p.produto.nome }}</td>
      <td>{{ p.qtde }}</td>
      <td>{{ p.valor_total|floatformat:"2" }}</td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td>&nbsp</td><td>Total</td>
      <td>{{ estadia.total_produtos|floatformat:"2" }}</td>
    </tr>
  </tfoot>
</table>
{% endif %}

{% if estadia.danos %}
<table class="list">
  <thead>
    <tr>
      <th colspan="3">
        <h4>Danos realizados</h4>
      </th>
    </tr>
    <tr>
      <th>Descrição</th>
      <th>Grave</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    {% for d in estadia.danos %}
    <tr>
      <td>{{ d.desc }}</td>
      <td>{% if d.grave %}Sim{% else %}Não{% endif %}</td>
      <td>{{ d.valor|floatformat:"2" }}</td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td>&nbsp</td><td>Total</td>
      <td>{{ estadia.total_danos|floatformat:"2" }}</td>
    </tr>
  </tfoot>
</table>
{% endif %}

{% endblock %}

quarto/templates/quarto/iniciar_estadia.html
{% extends "base.html" %}
{% block title %}Iniciando nova estadia{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.ui.datepicker-pt-BR.js"></script>
<script type="text/javascript" src="/static/js/iniciar_estadia.js"></script>
<link type="text/css" href="/static/css/smoothness/jquery-ui-1.8.18.custom.css" rel="stylesheet" />
<style type="text/css">
  #hospede_cpf {width: 110px;}

  #id_data_inicial, #id_data_final {width: 80px;}
</style>
{% endblock %}

{% block conteudo %}
<h3>Iniciando nova estadia</h3>

<form method="post" action=".">
  {% csrf_token %}
  {{ form.reserva }}
  <table>
    <tbody>
      <tr>
        <th>{{ form.data_inicial.label }}:</th>
        <td>{{ form.data_inicial }}</td>
        {% if form.data_inicial.errors %}
        <td class="errors">{{ form.data_inicial.errors }}</td>
        {% endif %}
      </tr>

      <tr>
        <th>{{ form.data_final.label }}:</th>
        <td>{{ form.data_final }}</td>
        {% if form.data_final.errors %}
        <td class="errors">{{ form.data_final.errors }}</td>
        {% endif %}
      </tr>
    </tbody>
  </table>

  <h3>Hospedes</h3>
  <table>
    <tr>
      <td>CPF:</td>
      <td><input id="hospede_cpf" type="text"/></td>
      <td><a id="add_hospede" class="button green" href="#">Adicionar</a></td>
    </tr>
  </table>

  <table id="hospede_list" class="list" style="width: 300px;">
    <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
  <input type="submit" value="{% if object %}Atualizar{% else %}Iniciar{% endif %}" />
</form>
{% endblock %}

quarto/templates/quarto/quarto_confirm_delete.html
{% extends "base.html" %}
{% block title %}Apagar Hospede{% endblock %}
{% block conteudo %}
<form action="." method="post">
  {% csrf_token %}
  <h3>Deseja apagar o Quarto "{{ object.nome }}" ?</h3>
  <input type="submit" value="Sim">
</form>
{% endblock %}

quarto/templates/quarto/quarto_form.html
{% extends "base.html" %}
{% block title %}{% if object %}Atualizando{% else %}Criando{% endif %} Quarto{% endblock %}
{% block conteudo %}
<h3>
  {% if object %}Atualizando{% else %}Criando{% endif %} Quarto
</h3>

<form method="post" action=".">
  {% include "form_snippet.html" %}
  <input type="button" value="Voltar" onclick="history.go(-1)">
  <input type="submit" value="{% if object %}Atualizar{% else %}Criar{% endif %}" />
</form>
{% endblock %}

quarto/templates/quarto/quarto_list.html
{% extends "base.html" %}
{% block title %}Quartos{% endblock %}
{% block conteudo %}
<a class="button green" href="add/">Adicionar</a>

{% if object_list %}
<table class="list">
  <thead>
    <tr>
      <th>Nome</th><th>Estado</th>
      <th>Preço</th><th>Estadia Atual</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.nome }}</td>
      <td>{{ object.get_estado_display }}</td>
      <td>{{ object.preco|floatformat:2 }}</td>
      <td>{% if object.estadia_atual %}
        <a href="{{ object.estadia_atual.get_absolute_url }}">Detalhes</a>
        {% endif %}
      </td>
      <td>
        <p style="padding: 0px; margin: 0px;">
          {% if object.estadia_atual %}
          <a class="button red" href="finalizar/{{ object.id }}/">Finalizar</a>
          <a class="button" href="consumo/{{ object.id }}/">Registrar Consumo</a>
          <a class="button" href="dano/{{ object.id }}/">Registrar Dano</a>
          {% else %}
          <a class="button" href="hospedar/{{ object.id }}/">Iniciar Estadia</a>
          {% endif %}
        </p>
        <p style="padding: 0px; margin: 7px 0px;">
          <a class="button" href="atualiza/{{ object.id }}/">Editar</a>
          <a class="button red" href="remove/{{ object.id }}/">Deletar</a>
        </p>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<div class="pagination">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="page-current">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
    {% endif %}
  </span>
</div>
{% endif %}

{% else %}
<h3>Nenhum quarto cadastrado</h3>
{% endif %}
{% endblock %}

quarto/templates/quarto/reg_dano.html
{% extends "base.html" %}
{% block title %}Registrar dano{% endblock %}
{% block conteudo %}
<h3>Registrar dano</h3>

<form method="post" action=".">
  {% csrf_token %}

  <table>
    {{ form.as_table }}
  </table>

  <input type="submit" value="Registrar" />
</form>
{% endblock %}

quarto/templates/quarto/relatorio.html
{% extends "base.html" %}
{% block title %}Relatório de Estadias{% endblock %}
{% block conteudo %}
<h2>Relatório de Estadias</h2>
{% for mes in relatorio %}
<h3>{{ mes.mes|date:"F/Y" }}</h3>

<table class="list">
  <thead>
    <tr>
      <th>Nome do quarto</th>
      <th>Data inicial</th>
      <th>Data final</th>
      <th>Valor total</th>
      <th>&nbsp</th>
    </tr>
  </thead>
  <tbody>
    {% for estadia in mes %}
    <tr>
      <td>{{ estadia.quarto.nome }}</td>
      <td>{{ estadia.data_inicial|date:"d/m/Y" }}</td>
      <td>{{ estadia.data_final|date:"d/m/Y" }}</td>
      <td>{{ estadia.valor_total }}</td>
      <td><a href="{{ estadia.get_absolute_url }}">Detalhes</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% empty %}
<h4>Nenhuma estadia para ser exibida</h4>
{% endfor %}

{% endblock %}