funcionario/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.conf.urls.defaults import patterns, include, url
from views import *
from decorators import acesso_ao_cargo

urlpatterns = patterns(
    '',
    url(r'^$', acesso_ao_cargo(ListaFuncionario.as_view(), 'g')),
    url(r'^add/$', acesso_ao_cargo(AddFuncionario.as_view(), 'g')),
    url(r'^atualiza/(?P<pk>\d+)/$', acesso_ao_cargo(AtualizaFuncionario.as_view(), 'g')),
    url(r'^remove/(?P<pk>\d+)/$', acesso_ao_cargo(RemoveFuncionario.as_view(), 'g')),
    url(r'^senha/(?P<pk>\d+)/$', acesso_ao_cargo(SenhaFuncionario.as_view(), 'g')),
)

urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^$', 'hotsys.views.home', name='home'),
    url(r'^produto/', include('hotsys.produto.urls')),
)

funcionario/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import hashlib
from django.db import models

FUNCIONARIO_TIPO = (
    ('g', "Gestor"),
    ('b', "Balconista"),
    ('r', "Recepcionista"))

class Funcionario(models.Model):
    nome = models.CharField(
        max_length=100,
        verbose_name="Nome")

    email = models.EmailField(
        verbose_name="E-Mail")

    tipo = models.CharField(
        max_length=1,
        choices=FUNCIONARIO_TIPO,
        verbose_name="Tipo")

    usuario = models.CharField(
        max_length=50,
        verbose_name="Usuário",
        unique=True)

    senha = models.CharField(max_length=40)

    ativo = models.BooleanField(
        default=True)
    cpf = models.CharField(
        max_length=16,
        verbose_name="CPF",
        null=True, blank=True)

    def set_senha(self, senha):
        """
        Guarda a senha no formado MD5SUM
        """
        self.senha = hashlib.md5(senha).hexdigest()

    def check_senha(self, senha):
        senha = hashlib.md5(senha).hexdigest()

        return self.senha == senha

    @property
    def is_active(self):
        return self.ativo

    def is_authenticated(self):
        return True

    class Meta:
        db_table = "funcionario"

funcionario/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

__all__ = ("AddFuncionarioForm", "AtualizaFuncionarioForm", "SenhaFuncionarioForm")

from django import forms
from models import *

class AddFuncionarioForm(forms.ModelForm):
    senha1 = forms.CharField(label=u"Senha",
                             widget=forms.PasswordInput)
    senha2 = forms.CharField(label=u"Confirmação de senha",
                             widget=forms.PasswordInput)

    def clean_senha2(self):
        senha1 = self.cleaned_data.get("senha1", "")
        senha2 = self.cleaned_data["senha2"]

        if senha1 != senha2:
            raise forms.ValidationError(u"As duas senhas não são iguais")
        return senha2

    def save(self, commit=True):
        user = super(AddFuncionarioForm, self).save(commit=False)
        user.set_senha(self.cleaned_data["senha1"])

        if commit:
            user.save()

        return user

    class Meta:
        model = Funcionario
        exclude = ('senha',)


class AtualizaFuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        exclude = ('senha',)

class SenhaFuncionarioForm(forms.Form):
    senha1 = forms.CharField(
        label=u"Nova senha",
        widget=forms.PasswordInput)

    senha2 = forms.CharField(
        label=u"Confirmação nova senha",
        widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SenhaFuncionarioForm, self).__init__(*args, **kwargs)

    def clean_senha2(self):
        senha1 = self.cleaned_data.get('senha1')
        senha2 = self.cleaned_data.get('senha2')

        if senha1 and senha2:
            if senha1 != senha2:
                raise forms.ValidationError(u"As senhas não conferem")
        return senha2

    def save(self, commit=True):
        self.user.set_senha(self.cleaned_data['senha1'])

        if commit:
            self.user.save()

        return self.user

funcionario/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

__all__ = ('AddFuncionario', 'ListaFuncionario',
           'AtualizaFuncionario', 'RemoveFuncionario',
           'SenhaFuncionario')

from models import *
from forms import *
from django.views.generic import (
    DeleteView, CreateView,
    UpdateView, ListView, FormView)

from django.shortcuts import get_object_or_404

class AddFuncionario(CreateView):
    model = Funcionario
    success_url = "/funcionario/"
    form_class = AddFuncionarioForm

class AtualizaFuncionario(UpdateView):
    model = Funcionario
    success_url = "/funcionario/"
    form_class = AtualizaFuncionarioForm

class RemoveFuncionario(DeleteView):
    model = Funcionario
    success_url = "/funcionario/"

class ListaFuncionario(ListView):
    model = Funcionario
    paginate_by = 20
    template_name = "funcionario/funcionario_list.html"

class SenhaFuncionario(FormView):
    success_url = "/funcionario/"
    template_name = "funcionario/senha.html"

    def get_object(self):
        return get_object_or_404(Funcionario, id=self.kwargs.get('pk'))

    def get_form(self, *args, **kwargs):
        return SenhaFuncionarioForm(self.get_object())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = SenhaFuncionarioForm(self.object, request.POST)
        
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

funcionario/templates/funcionario/funcionario_confirm_delete.html
{% extends "base.html" %}
{% block title %}Apagar Funcionário{% endblock %}
{% block conteudo %}
<form action="." method="post">
  {% csrf_token %}
  <h3>Deseja apagar o Funcionário "{{ object.nome }}" ?</h3>
  <input type="submit" value="Sim">
</form>
{% endblock %}

funcionario/templates/funcionario/funcionario_form.html
{% extends "base.html" %}
{% block title %}{% if object %}Atualizando{% else %}Criando{% endif %} Funcionário{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript">
  $(function(e) {
     $('#id_cpf').mask('999.999.999-99');
  });
</script>
{% endblock %}

{% block conteudo %}
<h3>
  {% if object %}Atualizando{% else %}Criando{% endif %} Funcionário
</h3>

<form method="post" action=".">
  {% include "form_snippet.html" %}
  <input type="button" value="Voltar" onclick="history.go(-1)">
  <input class="green button" type="submit" value="{% if object %}Atualizar{% else %}Criar{% endif %}" />
</form>
{% endblock %}

funcionario/templates/funcionario/funcionario_list.html
{% extends "base.html" %}
{% block title %}Funcionários{% endblock %}
{% block conteudo %}
<a href="add/" class="button green">Adicionar</a>

{% if object_list %}
<table class="list">
  <thead>
    <tr>
      <th>Nome</th><th>E-Mail</th>
      <th>Tipo</th>
      <th>Usuário</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.nome }}</td>
      <td>{{ object.email }}</td>
      <td>{{ object.get_tipo_display }}</td>
      <td>{{ object.usuario }}</td>
      <td>
        <a href="atualiza/{{ object.id }}" class="button">Editar</a>
        <a href="senha/{{ object.id }}" class="button">Alterar senha</a>
        <a href="remove/{{ object.id }}" class="button red">Deletar</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<div class="pagination">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="page-current">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
    {% endif %}
  </span>
</div>
{% endif %}

{% else %}
<h3>Nenhum funcionario cadastrado</h3>
{% endif %}
{% endblock %}

funcionario/templates/funcionario/senha.html
{% extends "base.html" %}
{% block title %}Alteração de senha de funcionário{% endblock %}
{% block conteudo %}
<h3>Alterar senha do funcionário</h3>

<form method="post" action=".">
  {% csrf_token %}

  <table>
    {{ form.as_table }}
  </table>

  <input type="submit" value="Alterar" />
</form>
{% endblock %}