hospede/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.conf.urls.defaults import patterns, include, url
from views import *

urlpatterns = patterns(
    '',
    url(r'^$', ListaHospede.as_view()),
    url(r'^add/$', AddHospede.as_view()),
    url(r'^atualiza/(?P<pk>\d+)/$', AtualizaHospede.as_view()),
    url(r'^remove/(?P<pk>\d+)/$', RemoveHospede.as_view()),
)

urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^$', 'hotsys.views.home', name='home'),
    url(r'^produto/', include('hotsys.produto.urls')),
)

hospede/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

__all__ = ('Hospede',)

from django.db import models

class Hospede(models.Model):
    nome = models.CharField(
        max_length=220,
        verbose_name="Nome completo")

    data_nasc = models.DateField(
        verbose_name="Data de nascimento")

    cpf = models.CharField(
        max_length=16,
        verbose_name="CPF",
        unique=True)

    telefone = models.CharField(
        max_length=16,
        verbose_name="Telefone",
        null=True, blank=True)

    logradouro = models.CharField(
        max_length=250,
        verbose_name="Logradouro")
    
    cidade = models.CharField(
        max_length=50,
        verbose_name="Cidade")

    necessidades = models.TextField(
        null=True, blank=True,
        verbose_name="Necessidades")

    observacoes = models.TextField(
        null=True, blank=True,
        verbose_name=u"Observações")
    
    class Meta:
        db_table = "hospede"
        ordering = ['nome']

hospede/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

__all__ = ('HospedeForm',)

from models import *
from django import forms
from django.contrib.localflavor.br.forms import BRCPFField

class HospedeForm(forms.ModelForm):
    cpf = BRCPFField(
        label="CPF",
        required=True,
        error_messages={'invalid': u"CPF Inválido",
                        'max_digits': "Este campo requer 11 digitos",
                        'digits_only': "Este campo aceita apenas digitos"})

    data_nasc = forms.DateField(
        label="Data de nascimento",
        required=True,
        widget=forms.DateInput(
            format="%d/%m/%Y",
            attrs={'size':'15','class': 'date'}))

    class Meta:
        model = Hospede

hospede/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Trabalho de conclusão de curso
# Alunos
#
# Wilson Pinto Júnior <wilsonpjunior@gmail.com>
# Mateus Fedrigo de Moura <mateusfedrigo@gmail.com>
# Jonathas Peixoto <jonathas.peixoto@gmail.com>
#
# Este programa é um software livre; você pode redistribui-lo e/ou 
# modifica-lo dentro dos termos da Licença Pública Geral GNU como 
# publicada pela Fundação do Software Livre (FSF); na versão 2 da 
# Licença, ou (na sua opnião) qualquer versão.

# Este programa é distribuido na esperança que possa ser  util, 
# mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer
# MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
# Licença Pública Geral GNU para maiores detalhes.
#
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

__all__ = ('AddHospede', 'ListaHospede', 'AtualizaHospede', 'RemoveHospede')

from models import *
from forms import *
from django.views.generic import DeleteView, CreateView, UpdateView, ListView

class AddHospede(CreateView):
    model = Hospede
    form_class = HospedeForm
    success_url = "/hospede/"

class AtualizaHospede(UpdateView):
    model = Hospede
    form_class = HospedeForm
    success_url = "/hospede/"

class RemoveHospede(DeleteView):
    model = Hospede
    success_url = "/hospede/"

class ListaHospede(ListView):
    model = Hospede
    paginate_by = 20

hospede/templates/hospede/hospede_confirm_delete.html
{% extends "base.html" %}
{% block title %}Apagar Hospede{% endblock %}
{% block conteudo %}
<form action="." method="post">
  {% csrf_token %}
  <h3>Deseja apagar o hóspede "{{ object.nome }}" ?</h3>
  <input type="submit" value="Sim">
</form>
{% endblock %}

hospede/templates/hospede/hospede_form.html
{% extends "base.html" %}
{% block title %}{% if object %}Atualizando{% else %}Criando{% endif %} Hospede{% endblock %}
{% block extrahead %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript">
  $(function(e) {
     $('#id_cpf').mask('999.999.999-99');
     $('#id_data_nasc').mask('99/99/9999');
     $('#id_telefone').mask('(99) 9999-9999');
  });
</script>
<style type="text/css">
  #id_necessidades, #id_observacoes {height: 50px; width: 500px;}
</style>
{% endblock %}
{% block conteudo %}
<h3>
  {% if object %}Atualizando{% else %}Criando{% endif %} Hospede
</h3>

<form method="post" action=".">
  {% csrf_token %}

  <table>
    <tbody>
      <tr>
        <th>* {{ form.cpf.label }}:</th>
        <td>{{ form.cpf }}</td>
        {% if form.cpf.errors %}
        <td class="errors">{{ form.cpf.errors }}</td>
        {% endif %}
      </tr><tr>
        <th>* {{ form.nome.label }}:</th>
        <td>{{ form.nome }}</td>
        {% if form.nome.errors %}
        <td class="errors">{{ form.nome.errors }}</td>
        {% endif %}
      </tr><tr>
        <th>* {{ form.data_nasc.label }}:</th>
        <td>{{ form.data_nasc }}</td>
        {% if form.data_nasc.errors %}
        <td class="errors">{{ form.data_nasc.errors }}</td>
        {% endif %}
      </tr><tr>
        <th>{{ form.telefone.label }}:</th>
        <td>{{ form.telefone }}</td>
        {% if form.telefone.errors %}
        <td class="errors">{{ form.telefone.errors }}</td>
        {% endif %}
      </tr>
    </tbody>
  </table>
  <h4>Endereço</h4>
  <table>
    <tbody>
      <tr>
        <th>* {{ form.logradouro.label }}:</th>
        <td>{{ form.logradouro }}</td>
        {% if form.logradouro.errors %}
        <td class="errors">{{ form.logradouro.errors }}</td>
        {% endif %}
      </tr><tr>
        <th>* {{ form.cidade.label }}:</th>
        <td>{{ form.cidade }}</td>
        {% if form.cidade.errors %}
        <td class="errors">{{ form.cidade.errors }}</td>
        {% endif %}
      </tr>
    </tbody>
  </table>

  <h4>{{ form.necessidades.label }}</h4>
  {% if form.necessidades.errors %}
  <p class="errors">{{ form.necessidades.errors }}</p>
  {% endif %}
  {{ form.necessidades }}

  <h4>{{ form.observacoes.label }}</h4>
  {% if form.observacoes.errors %}
  <p class="errors">{{ form.observacoes.errors }}</p>
  {% endif %}
  {{ form.observacoes }}

  <input type="submit" value="{% if object %}Atualizar{% else %}Criar{% endif %}" />
</form>
{% endblock %}

hospede/templates/hospede/hospede_list.html
{% extends "base.html" %}
{% block title %}Hóspedes{% endblock %}
{% block conteudo %}
<a class="button green" href="add/">Adicionar</a>

{% if object_list %}
<table class="list">
  <thead>
    <tr>
      <th>Nome</th><th>CPF</th>
      <th>Telefone</th><th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.nome }}</td>
      <td>{{ object.cpf }}</td>
      <td>{{ object.telefone }}</td>
      <td>
        <a href="atualiza/{{ object.id }}" class="button">Editar</a>
        <a href="remove/{{ object.id }}" class="button red">Deletar</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<div class="pagination">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="page-current">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
    {% endif %}
  </span>
</div>
{% endif %}

{% else %}
<h3>Nenhum hóspede cadastrado</h3>
{% endif %}
{% endblock %}